services:
  identity:
    build:
      context: .
      dockerfile: apps/api/identity/Dockerfile
    container_name: gymtrack-identity
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env
    image: kaiannn/gymtrack-identity:latest

  training-plan:
    build:
      context: .
      dockerfile: apps/api/training-plan/Dockerfile
    container_name: gymtrack-training-plan
    restart: always
    ports:
      - "8081:80"
    env_file:
      - .env
    image: kaiannn/gymtrack-training-plan:latest

  social:
    build:
      context: .
      dockerfile: apps/api/social/Dockerfile
    container_name: gymtrack-social
    restart: always
    ports:
      - "8082:80"
    env_file:
      - .env
    image: kaiannn/gymtrack-social:latest
