name: CI Quality Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          cache: true

      - name: Run Tests
        run: |
          go test -v ./apps/api/identity/...
          go test -v ./apps/api/training-plan/...
          go test -v ./libs/auth/...
          go test -v ./libs/db/...
          go test -v ./libs/config/...
          go test -v ./libs/storage/...
